### ISSUE TITLE
CLI commands fail for requireDir on Node v8

### ISSUE THREAD

**Issue by justinhough** [Shopify/slate-cli#129]
### Problem

There is a reported issue with Slate where requireDir fails on Node v8. https://github.com/Shopify/slate/issues/170

```
/Users/justin/Sites/Shopify/theme-name/node_modules/require-dir/index.js:97
            if (!require.extensions.hasOwnProperty(ext)) {
                                    ^

TypeError: require.extensions.hasOwnProperty is not a function
    at requireDir (/Users/justin/Sites/Shopify/theme-name/node_modules/require-dir/index.js:97:37)
    at Object.<anonymous> (/Users/justin/Sites/Shopify/augies-shopify/node_modules/@shopify/slate-tools/lib/gulpfile.js:39:1)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Liftoff.handleArguments (/Users/justin/Sites/Shopify/augies-shopify/node_modules/gulp/bin/gulp.js:116:3)
```
### Scope

This is related to all commands for Slate. `slate watch`, `slate start`, and `state zip`.

### Replication steps

1. Upgrade to Node `v8.0.0` and NPM `5.0.1`
2. Clean install Slate CLI `npm install -g @shopify/slate`
3. Initialize a new theme using Slate `slate theme new-theme`
4. Run `slate watch` or `slate start` or `slate zip`
5. Error occurs

### More Information

Reference issue first referenced under [Slate](https://github.com/Shopify/slate/issues/170) repo

**Comment by NathanPJF** [comment]
Resloved in https://github.com/Shopify/slate-cli/issues/130

**Comment by NathanPJF** [comment]
Fixed in https://github.com/Shopify/slate-tools/pull/66
